### PR TITLE
Style improvements

### PR DESCRIPTION
**Pull request by seballot**

### CODE REVIEW

**Comment by JohnMcLear** [comment]
This introduces a breaking change where webrtc is not visible by default yet there is an attempt to access video feed.  Try clear your cookies / settings and test.

**Comment by seballot** [comment]
Hi John ! Did you try with my latest change on etherpad? https://github.com/ether/etherpad-lite/pull/3744

**Comment by JohnMcLear** [comment]
@seballot no but we shouldn't introduce breaking changes to pre-existing plugins running on < 1.9..  :\

**Comment by seballot** [comment]
mmm, so we cannot refactor etherpad core... that's a difficulty of having the plugins system

Or what we can do keep the old css in the plugin, and overwrite it in etherpad core?

Or Isn't possible to say that webrtc 0.10 need at least etherpad 1.9?

The problem is bi directional

webrtc 0.10 does not support etherpad < 1.9
etherpad 1.9 does not support webrtc < 0.10

Do you have an idea of how to solve this? because using flexbox instead of all those absolute positioning is quite a big improvement in the code, would be good to keep it !

**Comment by seballot** [comment]
Ok I added the message if etherpad core is below 1.9
Also I made the plugin working on mobiles

**Comment by seballot** [comment]
Hi ! this one is ready btw, if you want to have a look !

**Comment by JohnMcLear** [comment]
Note that the plan is to get this in prior to 1.9.0 afaik, afaik it's due @ 1.8.3, let's see.

**Pull request merged**
