### PR TITLE
Test for enable-disable

### PR DESCRIPTION
**Pull request by orblivion**
Requires https://github.com/ether/etherpad-lite/pull/4042

### CODE REVIEW

**Comment by orblivion** [comment]
Obviously this is a small step, but once I get it on Travis I can test a lot more. I need to look into that next. I understand if you don't want to merge it until I get that working, but I wanted to get what I have here, as well as the accompanying PR in etherpad-lite, moving along.

**Comment by orblivion** [comment]
You may note that I've figured out how to make this work for Firefox and Chromium. The former requires a `{fake: true}` parameter to `getUserMedia`, the latter requires a CLI parameter. I haven't yet looked into the other browsers.

**Comment by JohnMcLear** [comment]
Did I give you the Travis access key?

**Comment by JohnMcLear** [comment]
Sorry saucelab access key?  As this is frontend..

**Comment by orblivion** [comment]
What's the plan then? Just run it manually until we figure out saucelabs?

**Comment by orblivion** [comment]
Oh, also this has junk in it from testing travis stuff. Please ask before merging stuff.

**Comment by JohnMcLear** [comment]
ah, as a rule I leave "WIP" until something is ready to merge :)....

**Comment by orblivion** [comment]
Cool, I'm happy to abide by that protocol :+1:

**Pull request merged**
